server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jehmes-microservice-ead/ead-config-server-repo
          default-label: main
          username: jehmes
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

encrypt:
  key: $B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp3s6