server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jehmes-microservice-ead/ead-config-server-repo
          default-label: main
          username: jehmes
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost